get_book_json = ['{\n'
                 '  "_id": {\n'
                 '    "$oid": "6043f630d708c98285cfd481"\n'
                 '  },\n'
                 '  "book_url": "https://www.goodreads.com/book/show/13335037-divergent",\n'
                 '  "title": "Divergent",\n'
                 '  "book_id": "13335037",\n'
                 '  "ISBN": "1234567890",\n'
                 '  "author_url": '
                 '"https://www.goodreads.com/author/show/4039811.Veronica_Roth",\n'
                 '  "author": "Veronica Roth",\n'
                 '  "rating": "4.18",\n'
                 '  "rating_count": "3040741",\n'
                 '  "review_count": "109348",\n'
                 '  "image_url": '
                 '"https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1588455221l/13335037._SY475_.jpg",\n'
                 '  "similar_books": [\n'
                 '    "https://www.goodreads.com/book/show/2767052-the-hunger-games",\n'
                 '    "https://www.goodreads.com/book/show/11870085-the-fault-in-our-stars",\n'
                 '    "https://www.goodreads.com/book/show/41865.Twilight",\n'
                 '    "https://www.goodreads.com/book/show/6186357-the-maze-runner",\n'
                 '    "https://www.goodreads.com/book/show/6148028-catching-fire",\n'
                 '    "https://www.goodreads.com/book/show/7260188-mockingjay",\n'
                 '    '
                 '"https://www.goodreads.com/book/show/3.Harry_Potter_and_the_Sorcerer_s_Stone",\n'
                 '    "https://www.goodreads.com/book/show/28187.The_Lightning_Thief",\n'
                 '    "https://www.goodreads.com/book/show/22537313-allegiant",\n'
                 '    "https://www.goodreads.com/book/show/256683.City_of_Bones",\n'
                 '    '
                 '"https://www.goodreads.com/book/show/18469079-divergent-official-illustrated-movie-companion",\n'
                 '    "https://www.goodreads.com/book/show/10507293-the-selection",\n'
                 '    "https://www.goodreads.com/book/show/10818853-fifty-shades-of-grey",\n'
                 '    "https://www.goodreads.com/book/show/6442769-paper-towns",\n'
                 '    "https://www.goodreads.com/book/show/3636.The_Giver",\n'
                 '    "https://www.goodreads.com/book/show/20349441-sampler-only",\n'
                 '    "https://www.goodreads.com/book/show/17623910-catching-fire",\n'
                 '    "https://www.goodreads.com/book/show/7735333-matched",\n'
                 '    "https://www.goodreads.com/book/show/2657.To_Kill_a_Mockingbird",\n'
                 '    "https://www.goodreads.com/book/show/25987085-maze-runner"\n'
                 '  ]\n'
                 '}']

get_author_json = ['{\n'
                   '  "_id": {\n'
                   '    "$oid": "6043f618d708c98285cfd479"\n'
                   '  },\n'
                   '  "author_url": "https://www.goodreads.com/author/show/15872.Rick_Riordan",\n'
                   '  "name": "Rick Riordan",\n'
                   '  "id": "15872",\n'
                   '  "rating": "5.0",\n'
                   '  "rating_count": "9181595",\n'
                   '  "review_count": "355900",\n'
                   '  "image_url": '
                   '"https://images.gr-assets.com/authors/1608906571p5/15872.jpg",\n'
                   '  "related_authors": [\n'
                   '    "https://www.goodreads.com/author/show/2493.Lois_Lowry",\n'
                   '    "https://www.goodreads.com/author/show/8349.Christopher_Paolini",\n'
                   '    "https://www.goodreads.com/author/show/10896.Eoin_Colfer",\n'
                   '    "https://www.goodreads.com/author/show/105630.Robert_Venditti",\n'
                   '    "https://www.goodreads.com/author/show/150038.Cassandra_Clare",\n'
                   '    "https://www.goodreads.com/author/show/153394.Suzanne_Collins",\n'
                   '    "https://www.goodreads.com/author/show/348878.James_Dashner",\n'
                   '    "https://www.goodreads.com/author/show/656983.J_R_R_Tolkien",\n'
                   '    "https://www.goodreads.com/author/show/941441.Stephenie_Meyer",\n'
                   '    "https://www.goodreads.com/author/show/1069006.C_S_Lewis",\n'
                   '    "https://www.goodreads.com/author/show/1077326.J_K_Rowling",\n'
                   '    "https://www.goodreads.com/author/show/1406384.John_Green",\n'
                   '    "https://www.goodreads.com/author/show/2987125.Kiera_Cass",\n'
                   '    "https://www.goodreads.com/author/show/3046613.Ransom_Riggs",\n'
                   '    "https://www.goodreads.com/author/show/4039811.Veronica_Roth",\n'
                   '    "https://www.goodreads.com/author/show/7074943.Victoria_Aveyard",\n'
                   '    "https://www.goodreads.com/author/show/9838621.Blue_Books"\n'
                   '  ],\n'
                   '  "author_books": [\n'
                   '    "https://www.goodreads.com/book/show/28187.The_Lightning_Thief",\n'
                   '    '
                   '"https://www.goodreads.com/book/show/2120932.The_Battle_of_the_Labyrinth",\n'
                   '    "https://www.goodreads.com/book/show/28186.The_Sea_of_Monsters",\n'
                   '    "https://www.goodreads.com/book/show/561456.The_Titan_s_Curse",\n'
                   '    "https://www.goodreads.com/book/show/12127750-the-mark-of-athena",\n'
                   '    "https://www.goodreads.com/book/show/7736182-the-lost-hero",\n'
                   '    "https://www.goodreads.com/book/show/4556058-the-last-olympian",\n'
                   '    "https://www.goodreads.com/book/show/9520360-the-son-of-neptune",\n'
                   '    "https://www.goodreads.com/book/show/7090447-the-red-pyramid",\n'
                   '    "https://www.goodreads.com/book/show/12127810-the-house-of-hades",\n'
                   '    "https://www.goodreads.com/book/show/52397.Parable_of_the_Sower",\n'
                   '    "https://www.goodreads.com/book/show/35068768-blackfish-city",\n'
                   '    "https://www.goodreads.com/book/show/55277625-the-last-fallen-star",\n'
                   '    "https://www.goodreads.com/book/show/43517256-city-of-the-plague-god",\n'
                   '    "https://www.goodreads.com/book/show/28962452-revenger",\n'
                   '    "https://www.goodreads.com/book/show/27824826-the-dry",\n'
                   '    '
                   '"https://www.goodreads.com/book/show/51323365-solutions-and-other-problems",\n'
                   '    "https://www.goodreads.com/book/show/36873145-le-assaggiatrici",\n'
                   '    "https://www.goodreads.com/book/show/9701194-i-promessi-sposi"\n'
                   '  ]\n'
                   '}']

put_book_json = ['{\n'
                 '  "_id": {\n'
                 '    "$oid": "6043f630d708c98285cfd481"\n'
                 '  },\n'
                 '  "book_url": "https://www.goodreads.com/book/show/13335037-divergent",\n'
                 '  "title": "Divergent",\n'
                 '  "book_id": "13335037",\n'
                 '  "ISBN": "1234567890",\n'
                 '  "author_url": '
                 '"https://www.goodreads.com/author/show/4039811.Veronica_Roth",\n'
                 '  "author": "Veronica Roth",\n'
                 '  "rating": "4.18",\n'
                 '  "rating_count": "3040741",\n'
                 '  "review_count": "109348",\n'
                 '  "image_url": '
                 '"https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1588455221l/13335037._SY475_.jpg",\n'
                 '  "similar_books": [\n'
                 '    "https://www.goodreads.com/book/show/2767052-the-hunger-games",\n'
                 '    "https://www.goodreads.com/book/show/11870085-the-fault-in-our-stars",\n'
                 '    "https://www.goodreads.com/book/show/41865.Twilight",\n'
                 '    "https://www.goodreads.com/book/show/6186357-the-maze-runner",\n'
                 '    "https://www.goodreads.com/book/show/6148028-catching-fire",\n'
                 '    "https://www.goodreads.com/book/show/7260188-mockingjay",\n'
                 '    '
                 '"https://www.goodreads.com/book/show/3.Harry_Potter_and_the_Sorcerer_s_Stone",\n'
                 '    "https://www.goodreads.com/book/show/28187.The_Lightning_Thief",\n'
                 '    "https://www.goodreads.com/book/show/22537313-allegiant",\n'
                 '    "https://www.goodreads.com/book/show/256683.City_of_Bones",\n'
                 '    '
                 '"https://www.goodreads.com/book/show/18469079-divergent-official-illustrated-movie-companion",\n'
                 '    "https://www.goodreads.com/book/show/10507293-the-selection",\n'
                 '    "https://www.goodreads.com/book/show/10818853-fifty-shades-of-grey",\n'
                 '    "https://www.goodreads.com/book/show/6442769-paper-towns",\n'
                 '    "https://www.goodreads.com/book/show/3636.The_Giver",\n'
                 '    "https://www.goodreads.com/book/show/20349441-sampler-only",\n'
                 '    "https://www.goodreads.com/book/show/17623910-catching-fire",\n'
                 '    "https://www.goodreads.com/book/show/7735333-matched",\n'
                 '    "https://www.goodreads.com/book/show/2657.To_Kill_a_Mockingbird",\n'
                 '    "https://www.goodreads.com/book/show/25987085-maze-runner"\n'
                 '  ]\n'
                 '}']

put_author_json = ['{\n'
                   '  "_id": {\n'
                   '    "$oid": "6043f618d708c98285cfd479"\n'
                   '  },\n'
                   '  "author_url": "https://www.goodreads.com/author/show/15872.Rick_Riordan",\n'
                   '  "name": "Rick Riordan",\n'
                   '  "id": "15872",\n'
                   '  "rating": "5.0",\n'
                   '  "rating_count": "9181595",\n'
                   '  "review_count": "355900",\n'
                   '  "image_url": '
                   '"https://images.gr-assets.com/authors/1608906571p5/15872.jpg",\n'
                   '  "related_authors": [\n'
                   '    "https://www.goodreads.com/author/show/2493.Lois_Lowry",\n'
                   '    "https://www.goodreads.com/author/show/8349.Christopher_Paolini",\n'
                   '    "https://www.goodreads.com/author/show/10896.Eoin_Colfer",\n'
                   '    "https://www.goodreads.com/author/show/105630.Robert_Venditti",\n'
                   '    "https://www.goodreads.com/author/show/150038.Cassandra_Clare",\n'
                   '    "https://www.goodreads.com/author/show/153394.Suzanne_Collins",\n'
                   '    "https://www.goodreads.com/author/show/348878.James_Dashner",\n'
                   '    "https://www.goodreads.com/author/show/656983.J_R_R_Tolkien",\n'
                   '    "https://www.goodreads.com/author/show/941441.Stephenie_Meyer",\n'
                   '    "https://www.goodreads.com/author/show/1069006.C_S_Lewis",\n'
                   '    "https://www.goodreads.com/author/show/1077326.J_K_Rowling",\n'
                   '    "https://www.goodreads.com/author/show/1406384.John_Green",\n'
                   '    "https://www.goodreads.com/author/show/2987125.Kiera_Cass",\n'
                   '    "https://www.goodreads.com/author/show/3046613.Ransom_Riggs",\n'
                   '    "https://www.goodreads.com/author/show/4039811.Veronica_Roth",\n'
                   '    "https://www.goodreads.com/author/show/7074943.Victoria_Aveyard",\n'
                   '    "https://www.goodreads.com/author/show/9838621.Blue_Books"\n'
                   '  ],\n'
                   '  "author_books": [\n'
                   '    "https://www.goodreads.com/book/show/28187.The_Lightning_Thief",\n'
                   '    '
                   '"https://www.goodreads.com/book/show/2120932.The_Battle_of_the_Labyrinth",\n'
                   '    "https://www.goodreads.com/book/show/28186.The_Sea_of_Monsters",\n'
                   '    "https://www.goodreads.com/book/show/561456.The_Titan_s_Curse",\n'
                   '    "https://www.goodreads.com/book/show/12127750-the-mark-of-athena",\n'
                   '    "https://www.goodreads.com/book/show/7736182-the-lost-hero",\n'
                   '    "https://www.goodreads.com/book/show/4556058-the-last-olympian",\n'
                   '    "https://www.goodreads.com/book/show/9520360-the-son-of-neptune",\n'
                   '    "https://www.goodreads.com/book/show/7090447-the-red-pyramid",\n'
                   '    "https://www.goodreads.com/book/show/12127810-the-house-of-hades",\n'
                   '    "https://www.goodreads.com/book/show/52397.Parable_of_the_Sower",\n'
                   '    "https://www.goodreads.com/book/show/35068768-blackfish-city",\n'
                   '    "https://www.goodreads.com/book/show/55277625-the-last-fallen-star",\n'
                   '    "https://www.goodreads.com/book/show/43517256-city-of-the-plague-god",\n'
                   '    "https://www.goodreads.com/book/show/28962452-revenger",\n'
                   '    "https://www.goodreads.com/book/show/27824826-the-dry",\n'
                   '    '
                   '"https://www.goodreads.com/book/show/51323365-solutions-and-other-problems",\n'
                   '    "https://www.goodreads.com/book/show/36873145-le-assaggiatrici",\n'
                   '    "https://www.goodreads.com/book/show/9701194-i-promessi-sposi"\n'
                   '  ]\n'
                   '}']

post_book_json = '{ "author_url": "https://www.goodreads.com/author/show/15872.Rick_Riordan", "name": "Rick Riordan", ' \
                 '"id": "678", "rating": "5.0", "rating_count": "9181595", "review_count": "355900", "image_url": ' \
                 '"https://images.gr-assets.com/authors/1608906571p5/15872.jpg" } '

post_books_json = '[ { "author_url": "https://www.goodreads.com/author/show/15872.Rick_Riordan", "name": "Rick ' \
                 'Riordan", "id": "678", "rating": "5.0", "rating_count": "9181595", "review_count": "355900", ' \
                 '"image_url": "https://images.gr-assets.com/authors/1608906571p5/15872.jpg" } ] '

post_author_json = '{ "author_url": "https://www.goodreads.com/author/show/15872.Rick_Riordan", "name": "Rick ' \
                   'Riordan", "id": "678", "rating": "5.0", "rating_count": "9181595", "review_count": "355900", ' \
                   '"image_url":  "https://images.gr-assets.com/authors/1608906571p5/15872.jpg" } '

post_authors_json = '[{ "author_url": "https://www.goodreads.com/author/show/15872.Rick_Riordan", "name": "Rick ' \
                   'Riordan", "id": "678", "rating": "5.0", "rating_count": "9181595", "review_count": "355900", ' \
                   '"image_url":  "https://images.gr-assets.com/authors/1608906571p5/15872.jpg" } ]'